# Generated by Django 5.1.9 on 2025-05-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="learning_objectives",
            field=models.TextField(
                blank=True, null=True, verbose_name="Learning Objectives"
            ),
        ),
    ]
