# Generated by Django 5.1.9 on 2025-05-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("logo", models.ImageField(upload_to="courses/logos/")),
                (
                    "programming_language",
                    models.CharField(
                        blank=True,
                        choices=[("PROGRAMMING_LANGUAGE_PYTHON", "Python")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEBEL_BEGINNER", "Начальный"),
                            ("LEBEL_INTERMEDIATE", "Средний"),
                            ("LEBEL_ADVANCED", "Продвинутый"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("is_published", models.BooleanField(default=False)),
                ("certificate_available", models.BooleanField(default=False)),
                (
                    "main_color",
                    models.CharField(
                        blank=True, help_text="HEX color code", max_length=20, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
