# Generated by Django 5.1.9 on 2025-05-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEVEL_BEGINNER", "Начальный"),
                    ("LEVEL_INTERMEDIATE", "Средний"),
                    ("LEVEL_ADVANCED", "Продвинутый"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
