# Generated by Django 5.1.9 on 2025-05-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_lesson_material_module_lesson_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
