# Generated by Django 5.1.9 on 2025-05-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_usercourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="short_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
