# Generated by Django 5.1.9 on 2025-05-29 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCourseLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STATUS_NOT_VIEWED", "Не просмотрено"),
                            ("STATUS_VIEWED", "Просмотрено"),
                            ("STATUS_IN_PROGRESS", "В процессе"),
                            ("STATUS_COMPLETED", "Завершен"),
                        ],
                        default="STATUS_NOT_VIEWED",
                        max_length=20,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.lesson"
                    ),
                ),
                (
                    "user_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.usercourse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
