# Generated by Django 5.1.9 on 2025-05-29 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_usercourselesson"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usercourse",
            unique_together={("user", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="usercourselesson",
            unique_together={("user_course", "lesson")},
        ),
        migrations.CreateModel(
            name="UserCourseLessonMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STATUS_NOT_COMPLETED", "Не завершено"),
                            ("STATUS_COMPLETED", "Завершено"),
                        ],
                        default="STATUS_NOT_COMPLETED",
                        max_length=20,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.material",
                    ),
                ),
                (
                    "user_course_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.usercourselesson",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_course_lesson", "material")},
            },
        ),
    ]
