# Generated by Django 5.1.9 on 2025-05-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_question_survey_answeroption_question_survey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercoursesurvey",
            name="status",
            field=models.CharField(
                choices=[
                    ("STATUS_NOT_COMPLETED_YET", "Не завершен"),
                    ("STATUS_COMPLETED_WITH_FAILS", "Завершен с ошибками"),
                    ("STATUS_COMPLETED", "Завершен"),
                ],
                default="STATUS_NOT_COMPLETED_YET",
                max_length=30,
            ),
        ),
    ]
