# Generated by Django 5.1.9 on 2025-05-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_usercoursesurvey_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercoursesurvey",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_course_surveys",
                to="courses.survey",
            ),
        ),
    ]
