# Generated by Django 5.1.9 on 2025-05-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_alter_usercoursesurvey_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranswer",
            name="status",
            field=models.CharField(
                choices=[
                    ("STATUS_NOT_COMPLETED_YET", "Не отвечено"),
                    ("STATUS_COMPLETED_WITH_FAILS", "Отвечено неверно"),
                    ("STATUS_COMPLETED", "Отвечено правильно"),
                ],
                default="STATUS_NOT_COMPLETED_YET",
                max_length=30,
            ),
        ),
    ]
